version: '3.1'
services:
  database:
    build:
      context: ./database/
    image: ${SHORTNAME}_database
    container_name: ${SHORTNAME}_database
    restart: always
    env_file: .env
  database_admin:
    build:
      context: ./database-admin/
    image: ${SHORTNAME}_database_admin
    container_name: ${SHORTNAME}_database_admin
    restart: always
    ports:
      - ${DATABASE_ADMIN_PORT}:${DATABASE_ADMIN_PORT}
  app:
    build:
      context: ./app/
    image: ${SHORTNAME}_app
    container_name: ${SHORTNAME}_app
    volumes:
      - app:/root
      - ${LOCAL_DIR}/app:/usr/src/app
    env_file: .env
    stdin_open: true
    tty: true
    ports:
      - ${APP_PORT}:${APP_PORT}
  admin:
    build:
      context: ./admin/
    image: ${SHORTNAME}_admin
    container_name: ${SHORTNAME}_admin
    env_file: .env
    restart: always
    stdin_open: true
    ports:
      - ${ADMIN_PORT}:${ADMIN_PORT}
