version: '3.1'
services:
  # db:
  #   container_name: postgres_custom
  #   build:
  #     context: ./models/postgres/
  #   restart: always
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  # adminer:
  #   container_name: adminer_custom
  #   build:
  #     context: ./models/adminer/
  #   restart: always
  #   ports:
  #     - 8080:8080
  # scala:
  #   container_name: scala_custom
  #   build:
  #     context: ./controllers/scala/
  #   env_file: .env
  #   stdin_open: true
  #   tty: true
  angular:
    container_name: angular_custom
    build:
      context: ./views/angular/
    restart: always
