version: '3.1'
services:
  database:
    build:
      context: ./${DATABASE_NAME}/
    image: ${DATABASE_NAME}
    container_name: ${ABBREVIATION}
    restart: always
    env_file: .env
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
  db_management:
    build:
      context: ./${DATABASE_MANAGEMENT_NAME}/
    image: ${DATABASE_MANAGEMENT_NAME}
    container_name: ${DATABASE_MANAGEMENT_NAME}
    restart: always
    ports:
      - ${DATABASE_MANAGEMENT_PORT}:${DATABASE_MANAGEMENT_PORT}
  controller:
    build:
      context: ./${CONTROLLER_NAME}/
    image: ${CONTROLLER_NAME}
    container_name: ${CONTROLLER_NAME}
    volumes:
      - ./${CONTROLLER_NAME}/${VOLUMES_NAME}/root:/root
      - ./${CONTROLLER_NAME}:/usr/src/app
    env_file: .env
    stdin_open: true
    tty: true
    ports:
      - ${CONTROLLER_PORT}:${CONTROLLER_PORT}
  # portal:
  #   build:
  #     context: ./${PORTAL_NAME}/
  #   image: ${PORTAL_NAME}
  #   container_name: ${PORTAL_NAME}
  #   env_file: .env
  #   restart: always
  #   stdin_open: true
  #   ports:
  #     - ${PORTAL_PORT}:${PORTAL_PORT}
  #   command: >
  #     /bin/sh -c
  #     "envsubst '
  #     $$ADMIN_PORT
  #     '< /etc/nginx/nginx.conf.template
  #     > /etc/nginx/nginx.conf
  #     && nginx -g 'daemon off;'"
