version: '3.1'
services:
  database_postgresql:
    build:
      context: ./database-postgresql/
    image: database-postgresql
    container_name: database-postgresql
    volumes:
      - ./database-postgresql/initialisation.sh:/docker-entrypoint-initdb.d/initialisation.sh
      - ./database-postgresql/initialisation:/docker-entrypoint-initdb.d/initialisation
    restart: on-failure
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:5432
  controller_scala:
    build:
      context: ./controller-scala/
    image: controller-scala
    container_name: controller-scala
    volumes:
      - ./controller-scala/volumes/root:/root
      - ./controller-scala:/usr/src/app
    env_file: .env
    stdin_open: true
    tty: true
    depends_on:
      - "database_postgresql"
    ports:
      - ${CONTROLLER_PORT}:${CONTROLLER_PORT}
  admin_react:
    build:
      context: ./admin-react/
    image: admin-react
    container_name: admin-react
    volumes:
      - ./admin-react:/app
      - ./README.md:/app/src/assets/README.md
    env_file: .env
    restart: on-failure
    stdin_open: true
    tty: true
    ports:
      - ${ADMIN_PORT}:3000
