version: '3.1'
services:
  database:
    build:
      context: ./database/
    image: database
    container_name: database
    volumes:
      - ./database/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./database/init:/docker-entrypoint-initdb.d/init
    restart: always
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:5432
  adminer:
    build:
      context: ./adminer/
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - "database"
    ports:
      - ${ADMINER_PORT}:8080
  controller:
    build:
      context: ./controller/
    image: controller
    container_name: controller
    volumes:
      - ./controller/volumes/root:/root
      - ./controller:/usr/src/app
    env_file: .env
    stdin_open: true
    tty: true
    depends_on:
      - "database"
    ports:
      - 80:${CONTROLLER_PORT}
  # admin:
  #   build:
  #     context: ./portal/
  #   image: portal
  #   container_name: portal
  #   env_file: .env
  #   restart: always
  #   stdin_open: true
  #   ports:
  #     - ${PORTAL_PORT}:${PORTAL_PORT}
  #   command: >
  #     /bin/sh -c
  #     "envsubst '
  #     $$ADMIN_PORT
  #     '< /etc/nginx/nginx.conf.template
  #     > /etc/nginx/nginx.conf
  #     && nginx -g 'daemon off;'"
