version: '3.1'
services:
  database_postgresql:
    build:
      context: ./database-postgresql/
    image: database-postgresql
    container_name: database-postgresql
    volumes:
      - ./database-postgresql/initialisation.sh:/docker-entrypoint-initdb.d/initialisation.sh
      - ./database-postgresql/initialisation:/docker-entrypoint-initdb.d/initialisation
    restart: always
    env_file: .env
    ports:
      - 5432:5432
  database_adminer:
    build:
      context: ./database-adminer/
    image: database-adminer
    container_name: database-adminer
    restart: always
    depends_on:
      - "database_postgresql"
    ports:
      - ${ADMINER_PORT}:8080
  controller_scala:
    build:
      context: ./controller-scala/
    image: controller-scala
    container_name: controller-scala
    volumes:
      - ./controller-scala/volumes/root:/root
      - ./controller-scala:/usr/src/app
    env_file: .env
    stdin_open: true
    tty: true
    depends_on:
      - "database_postgresql"
    ports:
      - 80:${CONTROLLER_PORT}
  # TODO: find a better-looking admin panel than ngx-admin !?
  # TODO: add dash and underscore characters to metakey to make it base 64 then make separator a colon
  # admin_angular:
  #   build:
  #     context: ./admin-angular/
  #   image: admin-angular
  #   container_name: admin-angular
  #   env_file: .env
  #   restart: always
  #   stdin_open: true
  #   ports:
  #     - ${PORTAL_PORT}:${PORTAL_PORT}
  #   command: >
  #     /bin/sh -c
  #     "envsubst '
  #     $$ADMIN_PORT
  #     '< /etc/nginx/nginx.conf.template
  #     > /etc/nginx/nginx.conf
  #     && nginx -g 'daemon off;'"
