version: '3.1'
services:
  database_postgresql:
    build:
      context: ./database-postgresql/
    image: database-postgresql
    container_name: database-postgresql
    volumes:
      - ./database-postgresql/initialisation.sh:/docker-entrypoint-initdb.d/initialisation.sh
      - ./database-postgresql/initialisation:/docker-entrypoint-initdb.d/initialisation
    restart: on-failure
    env_file: .env
    ports:
      - 5432:5432
  database_adminer:
    build:
      context: ./database-adminer/
    image: database-adminer
    container_name: database-adminer
    restart: on-failure
    depends_on:
      - "database_postgresql"
    ports:
      - ${DBADMIN_PORT}:8080
  controller_scala:
    build:
      context: ./controller-scala/
    image: controller-scala
    container_name: controller-scala
    volumes:
      - ./controller-scala/volumes/root:/root
      - ./controller-scala:/usr/src/app
    env_file: .env
    stdin_open: true
    tty: true
    depends_on:
      - "database_postgresql"
    ports:
      - ${CONTROLLER_PORT}:${CONTROLLER_PORT}
  admin_react:
    build:
      context: ./admin-react/
    image: admin-react
    container_name: admin-react
    volumes:
      - ./admin-react:/app
    env_file: .env
    restart: on-failure
    stdin_open: true
    depends_on:
      - "controller_scala"
    ports:
      - 80:3000
