version: '3.1'
services:
  database:
    env_file: .env
    build:
      context: ./${DATABASE_NAME}/
    image: ${DATABASE_NAME}
    container_name: ${ABBREVIATION}
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
  db_portal:
    environment:
      - ADMINER_DEFAULT_SERVER=${POSTGRES_HOST}
      - ADMINER_DESIGN='lucas-sandery'
    build:
      context: ./${DATABASE_MANAGEMENT_NAME}/
    image: ${DATABASE_MANAGEMENT_NAME}
    container_name: ${DATABASE_MANAGEMENT_NAME}
    restart: always
    ports:
      - ${DATABASE_MANAGEMENT_PORT}:${DATABASE_MANAGEMENT_PORT}
  controller:
    env_file: .env
    build:
      context: ./${CONTROLLER_NAME}/
    image: ${CONTROLLER_NAME}
    container_name: ${CONTROLLER_NAME}
    volumes:
      - ./${CONTROLLER_NAME}/${VOLUMES_NAME}/root:/root
      - ./${CONTROLLER_NAME}:/usr/src/app
    stdin_open: true
    tty: true
    ports:
      - ${CONTROLLER_PORT}:${CONTROLLER_PORT}
  # portal:
  #   build:
  #     context: ./${PORTAL_NAME}/
  #   image: ${PORTAL_NAME}
  #   container_name: ${PORTAL_NAME}
  #   env_file: .env
  #   restart: always
  #   stdin_open: true
  #   ports:
  #     - ${PORTAL_PORT}:${PORTAL_PORT}
  #   command: >
  #     /bin/sh -c
  #     "envsubst '
  #     $$ADMIN_PORT
  #     '< /etc/nginx/nginx.conf.template
  #     > /etc/nginx/nginx.conf
  #     && nginx -g 'daemon off;'"
