version: '3.1'
services:
  # database:
  #   container_name: database
  #   build:
  #     context: ./database/
  #   restart: always
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  # database_admin:
  #   container_name: database_admin
  #   build:
  #     context: ./database-admin/
  #   restart: always
  #   ports:
  #     - 8080:8080
  app:
    container_name: app
    build:
      context: ./app/
    stdin_open: true
    tty: true
  # admin:
  #   container_name: admin
  #   build:
  #     context: ./admin/
  #   restart: always
