version: '3.1'
services:
  database_postgresql:
    build:
      context: ./database-postgresql/
    image: database-postgresql
    container_name: database-postgresql
    volumes:
      - ./database-postgresql/initialise.sh:/docker-entrypoint-initdb.d/initialise.sh
      - ./database-postgresql/src:/docker-entrypoint-initdb.d/src
    restart: on-failure
    env_file: .env
    environment:
      - TZ=${PROJECT_TIMEZONE}
    ports:
      - ${POSTGRES_PORT}:5432
  controller_scala:
    build:
      context: ./controller-scala/
    image: controller-scala
    container_name: controller-scala
    volumes:
      - ./controller-scala/volumes/root:/root
      - ./controller-scala:/usr/src/app
      - ./storage/public:/usr/src/app/public
    env_file: .env
    stdin_open: true
    depends_on:
      - "database_postgresql"
    ports:
      - ${CONTROLLER_PORT}:${CONTROLLER_PORT}
  admin_react:
    build:
      context: ./admin-react/
    image: admin-react
    container_name: admin-react
    volumes:
      - ./admin-react:/app
      - ./README.md:/app/src/assets/README.md
      - ./storage/public:/app/public
    env_file: .env
    restart: on-failure
    stdin_open: true
    ports:
      - ${ADMIN_PORT}:${ADMIN_PORT}
      - ${ADMIN_CYPRESS_PORT}:${ADMIN_CYPRESS_PORT}
