openapi: "3.0.0"

info:
  title: Inventory Management System

servers:
  - url: http://localhost:8080/

paths:
  /users/list:
    post:
      summary: List the available users.
      tags:
        - users
        - list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: object
                  required:
                    - page_number
                    - page_length
                  properties:
                    page_number:
                      type: integer
                      format: int32
                      minimum: 1
                      default: 1
                    page_length:
                      type: integer
                      format: int32
                      minimum: 25
                      maximum: 100
                      default: 25
      responses:
        '200':
          description: A list of the available users.
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    type: array
                    required: true
                    items:
                      type: object
                      required:
                        - id
                        - record_id
                        - username
                        - password
                      properties:
                        id:
                          type: integer
                          format: int32
                        record_id:
                          type: integer
                          format: int32
                        username:
                          type: string
                        password:
                          type: string
        default:
          description: Unexpected error.
          content:
            application/json:
              schema:
                type: array
                required: true
                items:
                  type: object
                  required:
                    - code
                    - message
                  properties:
                    code:
                      type: integer
                      format: int32
                    message:
                      type: string
                    field:
                      type: string
